### ISSUE TITLE
Suporte a mais canais

### ISSUE THREAD

**Issue by RianFC** [git-jr/YouFlix#1]
O app só suporta canais com /user/ e não aceita os canais com /Channel/, poderia usar RegEx pois é mais eficaz

**Comment by git-jr** [comment]
Obrigado pelo comentário, realmente está correto,é algo fácil de corrigir irei fazê-lo em breve. Por ora o problema pode ser contornado adicionando "user/" antes da última palavra da URL do canal

**Comment by RianFC** [comment]
de nada tmj
